### ISSUE TITLE
Stop disabling abilities after level 5000

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/steamSummerMinigame#103]

**Comment by avanturist888** [comment]
Room # 2 7000+. Bosses dying too fast... Still no money while killing. How about of optional checkbox? So that players to decide for themselves to use or not their abilitys.

**Comment by EienSeihai** [comment]
After 5k if you need money, then you've probably mismanaged it all. Since our max has only ever been level 10k, speed is really the main goal after level 5k.

If the bosses are dying quickly, then that's good.

**Comment by avanturist888** [comment]
The dual situation - faster kill bosses with bombs after 5k - slowly killing bosses after 10k as a consequence of the shortage of gold.

**Comment by xPaw** [comment]
dc916efea361b17bcb40a359166afa1eee721c88 fixed this
