### ISSUE TITLE
Hide minor Updates to avoid accidental upgrades 

### ISSUE THREAD

**Issue by luanmuniz** [SteamDatabase/steamSummerMinigame#105]
What about optimize the upgrades?
When an update get high enough to allow higher updates we can hide the `div` of that upgrade to avoid mistakes when upgrade. For example.

When we have `Light Armor` equal to 10, we allow the second level of that same upgrade, when we do that we can hide the `Light Armor` since upgrade the second level is better to the player

At least the life seems to be simple as `if level equal to 10, hide it` but i'm not sure about the others. Its better to try track the value of each update and see if is better to upgrade one level or another based on the price/value of that upgrade
## Armor
- Hide after an upgrade reach level `10`
## Auto-Fire
- Hide `Auto-Fire Cannon` after reach level `20` because that way we have `Morale Boster` as pointed in https://github.com/SteamDatabase/steamSummerMinigame/issues/105#issuecomment-111879883
- Hide All Upgrades
## Damage
- Hide after an upgrade reach level `10`, pretty much after railgun, all `Armor Piercing Rounds` are irrelevant and `Explosive Rounds` gets too expensive
## Others

What should we do about `Lucky Shot` and `Boss Loot`?

**Comment by Xinayder** [comment]
That's a good idea. +1

edit: Perhaps we should disable the buy button from the abilities? or just remove them completely?

**Comment by luanmuniz** [comment]
I think remove is the best, that way we have more space in the box

I will try to calculate the best approach to hide the upgrades

**Comment by luanmuniz** [comment]
I will try to calculate the best approach to hide the upgrades

**Comment by matheod** [comment]
You could only show the more efficient upgrade, but there woudl be a problem.
Let's say we have A and B unlocked.
A is more efficient than B. But if you continue upgrade B you will unlock C, which is far more efficient than A. So maybe A may be more efficient in the short term, but maybe in the middle term, B then C is better. (if you see what I mean)

**Comment by wchill** [comment]
At this point we may as well just implement the autobuying, it's not too much extra work on top.

**Comment by luanmuniz** [comment]
@wchill Sure! I Have Fork this repo, i will try to implement that feature since i was the one that suggest it.

What you guys think about Auto-fire, should we Hide it after buy the first level? Or its useful somehow and i'm not seeing it?

**Comment by EienSeihai** [comment]
Didn't we fix the needing to buy an autofire to switch lanes already in https://github.com/SteamDatabase/steamSummerMinigame/pull/43?

**Comment by wchill** [comment]
You should still upgrade autofire to 10 because of abilities.

Cluster Bomb    For every enemy in your lane, 20% of their max health is dealt as damage.   Cluster Bomb icons falling from 'sky'   1 hour  1,000K(or, 1M)  Upgrade Auto-Fire Cannon to 10.

Morale Booster  Increases all damage done by players in your lane by 15%.   None    1 hour  10,000K(or, 10M)    Upgrade Auto-fire Cannon to 20.

Napalm  Damage all enemies in your lane over time for half their health.    Napalm icons falling from 'sky' 1 hour  2,000K(or, 2M)  Upgrade Auto-fire Cannon to 10.

**Comment by EienSeihai** [comment]
Ah right, but in that case shouldn't we go all the way to 20 at some point because of morale booster?

**Comment by luanmuniz** [comment]
How about the Upgrades of `Auto-Fire Cannon`? Do we need those? Or can we just Hide everything?
Reading [this](http://www.reddit.com/r/Steam/comments/39i0qc/psa_how_the_monster_game_works_an_indepth) look like we dont need anything else from that category.

How about `Lucky Shot` and `Boss Loot`?

By the way, i'm updating the issue content on the fly with the conclusions

**Comment by Znuff** [comment]
Warning, spaghetti code:

``` javascript
/* hide lower tier armor */
if ( jQuery("#upgr_8").length ) { jQuery("#upgr_0").hide(); }

if ( jQuery("#upgr_20").length ) { jQuery("#upgr_8").hide(); }

if ( jQuery("#upgr_23").length ) { jQuery("#upgr_20").hide(); }

/* hide lower tier auto-afk-dps */
if ( jQuery("#upgr_9").length ) { jQuery("#upgr_1").hide(); }

if ( jQuery("#upgr_21").length ) { jQuery("#upgr_9").hide(); }

if ( jQuery("#upgr_24").length ) { jQuery("#upgr_21").hide(); }

/* hide lower tier click-dps */
if ( jQuery("#upgr_10").length ) { jQuery("#upgr_2").hide(); }

if ( jQuery("#upgr_22").length ) { jQuery("#upgr_10").hide(); }

if ( jQuery("#upgr_25").length ) { jQuery("#upgr_22").hide(); }
```

**Comment by Znuff** [comment]
#125 should fix this

**Comment by luanmuniz** [comment]
The Pull Request was closed. I will close this too
