### ISSUE TITLE
Possible spam ability usage when game nears conclusion

### ISSUE THREAD

**Issue by EienSeihai** [SteamDatabase/steamSummerMinigame#106]
If there is a way to tell when the game has reached the last hour from the API (or by grabbing the time run so far) then maybe implement a spam of all abilities (minus nukes, raining gold, and all others automated to activate on certain levels).

Ones that would be useful are max elemental damage, cripple monster, decrease cooldowns (if this hasn't already been implemented to be used before nukes and such), throw money at screen, etc. 

If suggestion will be considered seriously, then I will compile list of optimal abilities to spam.

**Comment by GreatOldOne** [comment]
Possible workaround at https://github.com/SteamDatabase/steamSummerMinigame/pull/117

**Comment by Xinayder** [comment]
Instead of using the Minigame API to get the reset hour/game time, just check if the current time is 30 minutes away from the reset time.

**Comment by GreatOldOne** [comment]
That's exactly what I did.
It checks the GMT time for (15) and then check the time left based on what the user has set.

**Comment by iakat** [comment]
This has been implemented.
