### ISSUE TITLE
SmackTV();

### ISSUE THREAD

**Issue by ghost** [SteamDatabase/steamSummerMinigame#108]
Please, integrate the hidden easter egg.

Take this:
`$J('<div style="height: 52px; position: absolute; bottom: 85px; left: 828px; z-index: 12;" onclick="SmackTV();"><br><br><span style="font-size:10px; padding: 12px; color: gold;">Smack TV</span></div>').insertBefore('#row_bottom');`

**Comment by xPaw** [comment]
We've declined this already.

**Comment by ghost** [comment]
no

**Comment by ghost** [comment]
It's very important. DON'T CLOSE THIS IN 20 SECONDS, GOD DAMN IT.

**Comment by ghost** [comment]
meh, fuck u.
