### ISSUE TITLE
Requiring enums for Badge Items

### ISSUE THREAD

**Issue by GreatOldOne** [SteamDatabase/steamSummerMinigame#119]
We need enum for badge only items such as wormhole.
I would appreciate it If anyone has the time to read the minigame scripts and implement the enum.
Currently my wormhole implementation is awaiting it.

**Comment by ElDiabloWar3Evo** [comment]
Good idea !

**Comment by Xinayder** [comment]
Just added it, it's under ITEMS.
Closed, implemented via 669659d.
