### ISSUE TITLE
Add option to hide lower-tier upgrades

### ISSUE THREAD

**Issue by Znuff** [SteamDatabase/steamSummerMinigame#122]
As title says, could we get an option to hide lower-tier upgrades?

Armor:
# upgr_0 < #upgr_8 < #upgr_20 < #upgr_23

AFK:
# upgr_1 < #upgr_9 < #upgr_21 < #upgr_24

DPS:
# upgr_2 < #upgr_10 < #upgr_22 < #upgr_25

**Comment by ghost** [comment]
Why would you want to do this ?

**Comment by zuzak** [comment]
He wishes to hide lower-tier upgrades.

**Comment by iakat** [comment]
Duplicate of #105 
@Znuff Post those in #105

**Comment by ElDiabloWar3Evo** [comment]
Nice spot chauffer!

**Comment by chauffer** [comment]
Thanks, I made it myself. :blush.

**Comment by ElDiabloWar3Evo** [comment]
You good programmor!

**Comment by ElDiabloWar3Evo** [comment]
Thanks for makeing aweome script
