### ISSUE TITLE
Improve elemental lock

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/steamSummerMinigame#13]
And disable 3 other buttons.

**Comment by wchill** [comment]
https://github.com/wchill/steamSummerMinigame/commit/1f22a64a81fa1222d713ad3965de506375f81d15

**Comment by LeoVerto** [comment]
That seems to cover the basics, but I'd say we should add detection for existing manual locks, i.e. if a single element has all the levels even though it isn't the SteamID one.
