### ISSUE TITLE
Cluster bomb and napalm are not being used on high levels

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/steamSummerMinigame#134]
We're disabling these abilities for non-boss levels, but they are trying to be used on non-boss levels, which in result never happens and they go unused.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Hmm, looks more like if Level 5000 or above then enable it for Boss else disable them.
For Levels below disable them and the others for Boss and enable it for others.
