### ISSUE TITLE
Change disableCooldownIfRelevant into useDecreaseCooldownsIfRelevant and tweak it

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [SteamDatabase/steamSummerMinigame#136]
This Ability is called DecreaseCooldowns so to make Things cleaner, i suggest to rename the Function disableCooldownIfRelevant  into useDecreaseCooldownsIfRelevant. Also no need to disable the Ability.

Also ideally this should be used if another DecreaseCooldowns is already active (it stacks) and if another is active already, then cooldown of DecreaseCooldowns is also decreased if activated while another was activated.

Also perfect would be to use it, if as many as possible other Abilities was activated that currently have an Cooldown, because then all will benefit from it (-10 min cooldown).

Theoretically if 6 DecreaseCooldowns are activated together with other Abilities with Cooldowns, its possible to use all Abilities again instantly (because of -60 min) and because the DecreaseCooldowns Ability itself also then get a -60 min as well, its possible to spam it again ad infinitum.

Of Course for that to work many People must use the same Script, but if handled right this is the ultimative Thing, theoretically unlimited spamming of Abilities possible.

**Comment by iakat** [comment]
As far as I know, this has been fixed.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Yeah, also the Idea here was a bit different, but does not work because they not stack anymore, so can be closed anyway... ;)
