### ISSUE TITLE
Page doesn't reload if game fails to load

### ISSUE THREAD

**Issue by wmansir** [SteamDatabase/steamSummerMinigame#139]
The minigame will occasionally get stuck loading at 97/97 after a page reload and with the current script will stay that way until manually refreshed. It seems the current autorefresh function isn't setup until after the game loads, and even then it won't trigger unless the current target is defined and not a boss.

**Comment by kton** [comment]
Something like this ought to work:

```
setTimeout(function () {
  // m_rgGameData is 'undefined' if stuck at 97/97
  if (!g_Minigame.CurrentScene().m_rgGameData)
    window.location.reload(); // reloads page if game hasn't loaded
},30000); // evaluate after 30s delay
```

**Comment by xPaw** [comment]
Are you sure this isn't going to cause issues when the game is waiting for players?

**Comment by kton** [comment]
Yes.

![image](https://cloud.githubusercontent.com/assets/6096547/8158670/04809244-1314-11e5-8508-72e64addad4c.png)

**Comment by xPaw** [comment]
Feel free to make a pull request.
