### ISSUE TITLE
Got error while reloading and stuck on 97/97

### ISSUE THREAD

**Issue by vasia123** [SteamDatabase/steamSummerMinigame#142]
Error:
![2015-06-15 15-39-30 steam community monster summer sale - google chrome](https://cloud.githubusercontent.com/assets/801823/8160067/40276550-1375-11e5-9001-b7fbdea2f69f.png)

This line in script
![2015-06-15 15-40-01 steam community monster summer sale - google chrome](https://cloud.githubusercontent.com/assets/801823/8160068/405421f8-1375-11e5-9390-c4e6c2b9608b.png)

**Comment by fiskWasTaken** [comment]
This is not an error with the userscript itself; this is an error with the game and happens without a userscript.

**Comment by avanturist888** [comment]
May we reload page again if this happined?

**Comment by xPaw** [comment]
Will be fixed by #140
