### ISSUE TITLE
Lobby Broken

### ISSUE THREAD

**Issue by sordidfellow** [SteamDatabase/steamSummerMinigame#160]
If you join a game that's waiting on the first 1000 people, the script breaks the page.

Console message:
![lobby error](https://cloud.githubusercontent.com/assets/730944/8167225/71741d50-1362-11e5-8be3-fa295e3d59b0.png)

**Comment by GreatOldOne** [comment]
Well, that error isn't what's causing the problem, as it didn't receive the json data back from the minigame API yet.
Are you sure the lobby isn't lagged?

**Comment by GreatOldOne** [comment]
Also, try unchecking the AutoUpgrade boxes.

**Comment by Xinayder** [comment]
Try disabling the game throttle.
EDIT: @GreatOldOne auto-upgrades are disabled by default.

**Comment by sordidfellow** [comment]
Thanks @RockyTV - Unchecking Throttle Game Renderer fixed it.

Maybe that can be auto-disabled in lobby?

**Comment by GreatOldOne** [comment]
Or auto disabled by default.
