### ISSUE TITLE
Show next autoupgrade target

### ISSUE THREAD

**Issue by EhsanKia** [SteamDatabase/steamSummerMinigame#161]
Add some way to visually see which upgrade the script is planning to buy next.
This script has an implementation of it if you'd like to see
https://github.com/DannyDaemonic/SteamMonsterAutoUpgradeManager
Just a simple highlight would be good enough.

**Comment by thelulzy** [comment]
ensinm2's script now does this as well:
https://github.com/ensingm2/SteamMonsterGameScript

**Comment by iakat** [comment]
Fixed as of #200

**Comment by EhsanKia** [comment]
It would be nice if it it only showed the one thing that will be upgraded next, not what each "module" wants to upgrade next. As it is, it's pretty useless honestly, since we don't know which one is going to be triggered next out of the 3-4 different autobuy modules, and within a module, it's pretty easy to figure out which one is the best to buy (generally you want to keep them all at the same level).

**Comment by rossengeorgiev** [comment]
@EhsanKia highlighting shows the most cost effective upgrades. The automatic upgrading is done with additional rules and priorities, depending on the selected options.

**Comment by EhsanKia** [comment]
I realize that, but when I first suggested this change, the goal was to know what the script was going to buy next, figuring out the most cost efficient within a group is easy, the tricky part is knowing the most cost efficient across all the options.
