### ISSUE TITLE
Auto upgrade elemental ability

### ISSUE THREAD

**Issue by Xinayder** [SteamDatabase/steamSummerMinigame#162]
Was this suggested before? If not, I have two ideas for it:
- Auto purchase it whenever we have the money to upgrade;
- Auto purchase it when it is cost-effective (?)

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Auto purchase it whenever we have the money to upgrade, but please add an additional Option for it to disable/enable it.

Also only AutoUpgrade if only they have at least one Point there else upgrade the one with the least points first or so, probably better only do it if only one has points in it.

**Comment by Xinayder** [comment]
@K4r0qtuYNE5G4qgZ that was the idea.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
ok, yeah only to be sure ;)

**Comment by GreatOldOne** [comment]
It should be compared against Lucky Shot money cost.

**Comment by Xinayder** [comment]
@GreatOldOne so, check if elemental upgrade is more cost effective than Lucky Shot?
Or check if we have the money for lucky shot, if we do, buy it, otherwise buy elemental?

**Comment by GreatOldOne** [comment]
Cost effective. Elemental should be about 3 levels higher than Lucky Shot.

**Comment by Sosseres** [comment]
Please do not have Elemental upgrade higher than level 20. It is useless late game due to not stacking with crit as it says here:
https://github.com/SteamDatabase/steamSummerMinigame/issues/57

**Comment by K4r0qtuYNE5G4qgZ** [comment]
But it does increase Click Damage nicely 25x at lvl 16 and so on, so instead of eg. only 500k damage you have 12'500k damage on matching Element Lanes, that's a lot and its increasing in 1.5x Steps per Level.

And compared to Crit it's per tick, Crits are only sporadic...

**Comment by wchill** [comment]
Crit buffs take one minute to cool down, so investing in elemental early game is still a good strategy.

**Comment by rossengeorgiev** [comment]
@xPaw this was addressed in #222
