### ISSUE TITLE
getActiveAbilityLaneCount(ability) always returns 0

### ISSUE THREAD

**Issue by diwo** [SteamDatabase/steamSummerMinigame#164]

**Comment by GreatOldOne** [comment]
Proof?

**Comment by diwo** [comment]
Just an observation, taking a look into it

**Comment by K4r0qtuYNE5G4qgZ** [comment]
function getActiveAbilityLaneCount(ability) {
    var abilities = s().m_rgGameData.lanes[s().m_rgPlayerData.current_lane].active_player_abilities;
    var count = 0;
    for(var i = 0; i < abilities.length; i++) {
        if(abilities[i].ability != ability || abilities[i].timestamp_done < Date.now()) {
            continue;
        }
        count++;
    }
    return count;
}

Where?

If abilities.length is not always 0, then it will return count, so i don't see where it should be?

**Comment by diwo** [comment]
`abilities[i].timestamp_done < Date.now()` is always true

**Comment by iakat** [comment]
04494e65a8c757761dc086aea49bbfd98858f36c

**Comment by GreatOldOne** [comment]
Yes, since the loop tick is 1 second it will always be true.
I just this to be reverted.

**Comment by xPaw** [comment]
@diwo Is your local PC time correct? http://time.is

**Comment by K4r0qtuYNE5G4qgZ** [comment]
yeah i supposed that one too also but removed it then again

**Comment by GreatOldOne** [comment]
Date.now() returns an int32 in seconds since epoch.
Since our minimum loop time is 1 second, it will always be different.
Therefore, @diwo is correct.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
differrent ok, but is it always higher?

yeah, probably yes LOL!

**Comment by xPaw** [comment]
Date.now() returns milliseconds, is that why it's always true?

**Comment by GreatOldOne** [comment]
Date.now() will always be higher by 1 second (if the function is executed every loop)..
Even if it didn't return milisecs.

**Comment by xPaw** [comment]
Does that matter though?

**Comment by K4r0qtuYNE5G4qgZ** [comment]
yeah, its because date.now is guaranteed to be ahead of any prior Actions, so yeah of course always newer/higher than any Actions.

**Comment by GreatOldOne** [comment]
Yup, cache becomes obsolete on a second base.
It does more work for absolutely nothing.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
@xPaw
Well if its always true, for what check it?

Also i don't know what this currently affects.

**Comment by xPaw** [comment]
We can try using g_Minigame.m_CurrentScene.m_rgGameData.timestamp

**Comment by GreatOldOne** [comment]
But we don't want a cache longer than 1 second, since most abilities are on 5 seconds, do we?

**Comment by K4r0qtuYNE5G4qgZ** [comment]
But if this would really always return 0

then

why 

function tryUsingAbility(itemId, checkInLane) {
    if (!canUseAbility(itemId)) {
        return false;
    }

```
if (checkInLane && getActiveAbilityLaneCount(itemId) > 0) {
    return false;
}

triggerAbility(itemId);

return true;
```

}

Actually works?

**Comment by GreatOldOne** [comment]
I don't have any abilities using checkInLane right now.
If you can confirm it's working, we can close this one.

**Comment by diwo** [comment]
`tryUsingAbility` doesn't "work" in the sense that it'll never exit in the 2nd conditional, and the ability is allowed to be used even when it's already active.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Well, at least

```
// check if Medics is purchased and cooled down
if (tryUsingAbility(ABILITIES.MEDICS)) {
    advLog('Medics is purchased, cooled down. Trigger it.', 2);
}
```

uses function tryUsingAbility and this one also uses && getActiveAbilityLaneCount(itemId) > 0 so it can't return always 0?

**Comment by xPaw** [comment]
See 81a96bae18442ced3a6a93acc89f3d39733f4b3a

**Comment by GreatOldOne** [comment]
It does't. You must pass true as the second argument to tryUsingAbility().

**Comment by diwo** [comment]
Why does timestamp_done need to be checked at all? Isn't active_player_abilities updated regularly?

**Comment by diwo** [comment]
for reference

```
+function getCurrentTime() {
+   return s().m_rgGameData.timestamp;
+}
+
```

**Comment by GreatOldOne** [comment]
Yeah, I don't understand why it needs that check.

**Comment by diwo** [comment]
I think it's for when the ability has expired so it's no longer active in the current wave

**Comment by diwo** [comment]
Your fix might work, let me try it out

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Well ok, i see it now, this check actually doesn't affect anything at all even if always 0 because it's "||" only.

**Comment by diwo** [comment]
@xPaw https://github.com/SteamDatabase/steamSummerMinigame/commit/81a96bae18442ced3a6a93acc89f3d39733f4b3a#diff-2400c5b9c09e41abca684af32c0de223R1437
shouldn't it be less than?

EDIT: ignore above

**Comment by xPaw** [comment]
Yeah I think it is.

**Comment by GreatOldOne** [comment]
timestamp_done is the time that ability will cease, no? If yes, his code is correct "greater than".

**Comment by xPaw** [comment]
Here's what Valve does: https://github.com/SteamDatabase/SteamTracking/blob/0bdcf77ca4575c5b600c4b056ef14904e925b500/Scripts/MiniGame/TowerAttack/running.js#L830-L835

**Comment by diwo** [comment]
just tested it with:

```
function getActiveAbilityLaneCount(ability) {
    var abilities = s().m_rgGameData.lanes[s().m_rgPlayerData.current_lane].active_player_abilities;
    var count = 0;
    for(var i = 0; i < abilities.length; i++) {
        if(abilities[i].ability != ability || abilities[i].timestamp_done < s().m_rgGameData.timestamp) {
            continue;
        }
        count++;
    }
    if (ability === ABILITIES.MEDICS) {
        console.log('ability: ' + ability + '  count: ' + count);
    }
    return count;
}
```

numbers seem to match up with UI

**Comment by xPaw** [comment]
Wait, are you sure https://github.com/SteamDatabase/steamSummerMinigame/commit/81a96bae18442ced3a6a93acc89f3d39733f4b3a#diff-2400c5b9c09e41abca684af32c0de223R1437 wasn't correct?

**Comment by diwo** [comment]
Tried it with greaterThan first but got wrong numbers until flipped

**Comment by GreatOldOne** [comment]
What's timestamp_done then?

**Comment by GreatOldOne** [comment]
Out of curiosity remove that second check and leave it:

if(abilities[i].ability != ability) {

Tell me if that works.

**Comment by xPaw** [comment]
@diwo Using my complete code (where it counts inside the if, without continue)?

**Comment by K4r0qtuYNE5G4qgZ** [comment]
@GreatOldOne 

Yeah, its what i also thinking, it doesn't affect anything there, so remove it would be the same. LOL!

**Comment by diwo** [comment]
Checked out 81a96ba and removed the timestamp check from getActiveAbilityLaneCount, numbers still seem to be correct, even with the ability expiring case

**Comment by xPaw** [comment]
I think it's safer to keep it in case the game lags.

**Comment by iakat** [comment]
Seems to be solved.

**Comment by diwo** [comment]
@xPaw agreed, if timestamp_done does what it says it should do, the implementation looks good
