### ISSUE TITLE
Enum State

### ISSUE THREAD

**Issue by GreatOldOne** [SteamDatabase/steamSummerMinigame#165]
``` javascript
if(status != 2)
{
    return;
}
```

This is just ugly.
Instead create an enum for the game state.

**Comment by Xinayder** [comment]
Closed #165.
Fixed via 84199c57006bf883f4eba294de9e2e26ca6ac815.

**Comment by GreatOldOne** [comment]
What's GAME_STATUS 0, any idea?

**Comment by Xinayder** [comment]
@GreatOldOne nothing. 
`g_Minigame.GetMiniGameStatusString(0);` returns an empty string.

**Comment by xPaw** [comment]
Here's actual enum:

```
k_EMiniGameStatus_WaitingForPlayers = 1
k_EMiniGameStatus_Running = 2
k_EMiniGameStatus_Ended = 3
```

**Comment by Xinayder** [comment]
EDIT: what? It's not `tuningData.json`, it's the protobuf.
EDIT2: here's the complete enum:

```
enum EMiniGameStatus
{
    k_EMiniGameStatus_Invalid = 0;
    k_EMiniGameStatus_WaitingForPlayers = 1;
    k_EMiniGameStatus_Running = 2;
    k_EMiniGameStatus_Ended = 3;
}
```
