### ISSUE TITLE
Too many abilities being used simultaneously.

### ISSUE THREAD

**Issue by Stardrinker** [SteamDatabase/steamSummerMinigame#174]
This problem is exacerbated by the ability that resets everyones cooldowns. Easiest way to deal with this would be to only have a 10% chance to fire on each pass on abilities that are negatively affected by being spammed, e.g. Napalm, Cluster Bomb, Nuke, Cripple Spawner, Cripple Monster, and to a lesser extent, Medics, Decrease Cooldowns, Good Luck Charms, Resurrection, God Mode.

**Comment by Xinayder** [comment]
What's the problem?

**Comment by Stardrinker** [comment]
Hmm, I guess it's more of an optimization issue than it is a game-breaking issue. I just think that going through levels will be consistently faster if the pool of available nuke abilities can be kept at a reasonable level.

The % chance to trigger can be played around with.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
yeah, currently its like Nuke, Napalm, Clusterbombs are triggered almost together, same time, its better to delay them a bit. Perhaps based on Targethealth? So that not all are triggered same Time.

**Comment by Stardrinker** [comment]
The level 7510 boss in room 41671 just now took almost one minute to kill because noone had any nukes.

**Comment by smartalco** [comment]
This also effects non-stacking abilities, which was the cause of me mistakenly identifying a bug I attempted to fix in https://github.com/SteamDatabase/steamSummerMinigame/pull/193.

I think (for non-stacking) the biggest thing this effects is the Max Elemental Damage power, but also has effects on Revive and Decrease Cooldown.

It'll take some trial and error to find the right balance of how often to use abilities.  I'd probably try something like if the last number in the game level matches the last number in your Steam ID, then have like a 25% chance to try.  If no one uses shit on the first tick, increase the percentage to 100%.  If no one uses it after that, open up the range (last digit of level = last digit of Steam ID or last digit of Steam ID + 1).  Etc.  Something to where it's going to be guaranteed to be used within 4-6 ticks if the odds don't play out in the first couple.

**Comment by wchill** [comment]
I would try simple RNG for now and see how things go from there. The criteria for choosing whether to use can always be changed, but it's important to ability spam is curtailed ASAP.

Example code: https://github.com/wchill/steamSummerMinigame/commit/32685d2b243b8ece23d0a0e33973559704bc6522

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I also noticed that with the new Cooldown handler i added, they get automatically spreaded a bit because some will have decreased Cooldown while other not, so they get distributed a bit automatically, after a while, so it's a positive Side Effect of it somehow. But only affects Nuke, Napalm and Clusterbomb of course.

I also like the Idea of @smartalco this would distribute the usage a bit over Levels.

Perhaps also distribute them also over Lanes?

**Comment by Xinhuan** [comment]
I think this problem only exists if _a lot_ of people are using the same script in the same room, all of which are trying to use the same ability on the same monster. In rooms with only 100 scripters or less, this problem doesn't really exist, compared to rooms with 700 scripters - if you take this into account, the % chance of using a nuke should be based on the number of scripters. Maybe inversely scale the % chance with the number of active users in the room.

**Comment by Stardrinker** [comment]
It's also a latency problem, since the server can accept multiple ability uses as valid if they reach the server within a small enough time frame. Then you have the "Like New" ability that resets everyones cooldowns at once and creates a situation where almost everyone fires all their nukes at once, and then they are all on cooldown at the same time.
Even delaying the skill usage just a fraction of a second should be enough for the game data to update and skills can be triggered more accurately.

**Comment by Stardrinker** [comment]
Day 6 seems to have changed some mechanics of level transitions and DPS. We are now skipping multiple levels per tick. My theory is that our DPS is bleeding through to the next level and the next one after that. If that's true, then this may not be as big a problem anymore.

**Comment by xPaw** [comment]
They increased server tickrate, that's why we're flying through levels.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
yeah its crazy 2-4 seconds a level and beyond 700 already... ;)

Also new cooldown + Ability is working great, including the cooldown itself, many use the same script its perfect symbiosys...

**Comment by iakat** [comment]
This isn't an issue anymore.
