### ISSUE TITLE
Really bad performance compared to yesterday

### ISSUE THREAD

**Issue by luanmuniz** [SteamDatabase/steamSummerMinigame#178]
Hi Guys.

Yesterday the script was not this slow, something got into the code that its getting the performance really bad

**Comment by iakat** [comment]
Based on?

**Comment by xPaw** [comment]
It's not lag, renderer is throttled.

**Comment by luanmuniz** [comment]
@xPaw What do you mean?

**Comment by xPaw** [comment]
"Throttle game renderer" option.

**Comment by Mustek** [comment]
![http://up.mustek.be/1434402153Z.png](http://up.mustek.be/1434402153Z.png)

**Comment by luanmuniz** [comment]
Got it, sorry to open the issue, i did not saw this before. Thank you!
