### ISSUE TITLE
Use nuke on bosses on high levels (if not raining gold level)

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/steamSummerMinigame#181]

**Comment by GreatOldOne** [comment]
Anyone assigned to this one yet?

**Comment by xPaw** [comment]
Feel free to take it

**Comment by GreatOldOne** [comment]
What level should I use to start triggering this?

**Comment by xPaw** [comment]
See CONTROL.speedThreshold

**Comment by GreatOldOne** [comment]
This one can be closed as it implemented with https://github.com/SteamDatabase/steamSummerMinigame/pull/241
