### ISSUE TITLE
Make config variables toggleable on the page

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/steamSummerMinigame#19]
Store them in localstorage

**Comment by 1RV34** [comment]
`isAlreadyRunning` should not be part of config right? seems like internal variable

asking because it seems to be up there together with other toggables

**Comment by LeoVerto** [comment]
@1RV34 No, it should probably be global to prevent multiple instances of the script running.

**Comment by 1RV34** [comment]
So store in localStorage like the others?

**Comment by xPaw** [comment]
@wchill said he will look into options

**Comment by LeoVerto** [comment]
No, keep it as a global variable in the JS.

**Comment by 1RV34** [comment]
ah alright then, i'll continue on it now

**Comment by wchill** [comment]
Closed by #55
