### ISSUE TITLE
Upgrade click before dps?

### ISSUE THREAD

**Issue by tleunen** [SteamDatabase/steamSummerMinigame#192]
Would it be better to upgrade click skills before dps, because we're making more damages with clicks I think.

Or we could go further and detect which one is giving the best damage.

What do you think?

**Comment by amatecha** [comment]
yeah agree, the damage per sec with clicks is wayyy higher than DPS skill

**Comment by djmarcin** [comment]
The problem with #173 and #194 is that it should be scaling the click damage to get the effective DPS given click rate.  They also don't buy lucky shot or elementals.  This script appears to do it correctly: https://github.com/DannyDaemonic/SteamMonsterAutoUpgradeManager

**Comment by iakat** [comment]
This is already the case in https://github.com/SteamDatabase/steamSummerMinigame/blob/master/autoPlay.user.js#L463
Please open another issue if the priority checks are not working.
