### ISSUE TITLE
"Remove Interface" option breaks script UI if unchecked

### ISSUE THREAD

**Issue by sordidfellow** [SteamDatabase/steamSummerMinigame#195]
If you make the mistake of turning off Remove Interface, you cannot undo your mistake because of this:
![image](https://cloud.githubusercontent.com/assets/730944/8173829/f61045c6-1398-11e5-9070-b99fd8e8f614.png)

Scrolling and changing window size did not help.

Edit to add: Version 4.4.7 in Tampermonkey in Chrome

**Comment by iakat** [comment]
Closed by #198
