### ISSUE TITLE
In speed mode, don't waste raining gold if its not a raining gold level

### ISSUE THREAD

**Issue by ayonix** [SteamDatabase/steamSummerMinigame#196]
Raining gold seems to be starving for us (>= level 10k) and they are wasted on bosses that get crippled a second later.
It should thus only be used in levels where they are meant to be farmed, to get a better economy in later levels.
Should I add it?

**Comment by EienSeihai** [comment]
If possible, do it. Any optimizations are welcomed.

**Comment by iakat** [comment]
> It should thus only be used in levels where they are meant to be farmed

Such as?

**Comment by ayonix** [comment]
https://github.com/SteamDatabase/steamSummerMinigame/blob/master/autoPlay.user.js#L143 
`level < speedThreshold || level % rainingRounds == 0;`

**Comment by kaetemi** [comment]
&& (level < CONTROL.speedThreshold || level % CONTROL.rainingRounds === 0)

Related pull request https://github.com/SteamDatabase/steamSummerMinigame/pull/159 does this as well.

**Comment by ayonix** [comment]
PR #189 adds this as well as I've just seen. 
There's a comment to disable gold rain in the first 100 levels completely, maybe that should be discussed as well.
#159 looks good and should be used in favour of my PR.

**Comment by kaetemi** [comment]
Usage of gold rain under these rules matches nicely with the drop rate with the addition of the hp treshold lowering.

**Comment by ayonix** [comment]
Since it is added  (https://github.com/SteamDatabase/steamSummerMinigame/blob/master/autoPlay.user.js#L1281)  now, I will close this.
You should still consider if @kaetemi 's change to use raining gold if it's progressing slowly is an even better approach.
