### ISSUE TITLE
Inefficient gold farming because of different scripts?

### ISSUE THREAD

**Issue by garfieldbanks** [SteamDatabase/steamSummerMinigame#203]
https://steamcommunity.com/groups/MSG2015/discussions/0/598198356177708591/

https://github.com/ensingm2/SteamMonsterGameScript/issues/100

**Comment by lunboks** [comment]
PR #189 was already merged, so the thing I mentioned about this script using Raining Gold on every level in speed mode is no longer true

**Comment by iakat** [comment]
I am not able to fix this. @wchill's code is not in sync with other people's development and people have been suggested to use SteamDB as more up to date

**Comment by wchill** [comment]
#189 is an implementation of RG ratelimiting during speedmode from my fork. The only thing that's different here between my fork and SteamDB is the frequency of raining gold rounds, as I have changed mine to every 250. (I can change this back quickly, but I felt 250 made more sense.)

The only change that needs to be made here is to make sure all scripts are set to the same RG round frequency.
