### ISSUE TITLE
[Suggestion] Have the scripts display a link on the game page to your room's IRC channel

### ISSUE THREAD

**Issue by thelulzy** [SteamDatabase/steamSummerMinigame#206]
This was originally posted here: https://github.com/wchill/steamSummerMinigame/issues/169
Credit to meekmeekmeek, I just thought I was a great idea which needed visibility on all the major scripts.

I know most of the "official" rooms have dedicated steam groups to chat in. We could also generate links (through a web-irc client website like Mibbit) and if the script added a link on the page, more people would tend to join them.

doing it for an IRC channel would be easy, since you'd just generate the URL based on the room number, even if the channel doesn't exist yet (someone familiar with IRC could go create it then):

```
http://mibbit.com/?channel=%23<channel_name (w/o "#")>&server=<server_address>
```

**Comment by thelulzy** [comment]
Wow, the IRC idea would be a great way to coordinate a room's efforts!

Instead of complicating it with an official channel name or room name the URL could simply have the MSG, or something similar.

**Comment by xPaw** [comment]
We don't have enough man power to moderate through this, and for the past few days people who wanted to join a game was able to do so, let's keep it that way.

**Comment by thelulzy** [comment]
What? No moderation is necessary here. This allows people who are already in a specific game room to communicate with those also in the same game room. It has nothing to do with getting into a game and wouldn't impede that or require additional oversight. 

I was implemented here in ensingm2's script: https://github.com/ensingm2/SteamMonsterGameScript/commit/61a09298ffb0c2c7887024bc4c8d17b8999be4df
