### ISSUE TITLE
[Bug] New Pull Requests will all be marked as fail because of Error's in leaderboard.user.js

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [SteamDatabase/steamSummerMinigame#209]
The command "jshint autoPlay.user.js" exited with 0.
0.33s$ jshint leaderboard.user.js
leaderboard.user.js: line 62, col 40, Missing semicolon.
leaderboard.user.js: line 111, col 5, 'GM_xmlhttpRequest' is not defined.
2 errors
The command "jshint leaderboard.user.js" exited with 2.

**Comment by wchill** [comment]
Pull requests will not fail as they can still be merged. Travis CI is used as a guideline for whether to merge.

That being said, this should still be fixed.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Well, with fail i mean they all get marked as fail, not that they can't be merged at all.

**Comment by iakat** [comment]
I'm aware. I'll fix it asap.
