### ISSUE TITLE
Make separated centrally coordinated auto-join script

### ISSUE THREAD

**Issue by glukki** [SteamDatabase/steamSummerMinigame#210]
That script would work only on `http://steamcommunity.com/minigame/`
It would connect with websocket to some server and wait for incoming message.
Then, in the same time, server would send room ID to the clients, so they could run `JoinGame(room)`.

Do we need that thing as a side-script?

I can run the server and make client- and server-side things

**Comment by iakat** [comment]
We do not do external requests.

**Comment by glukki** [comment]
But the `leaderboard.user.js`? o.O

**Comment by Js41637** [comment]
That's not in the main script.

**Comment by glukki** [comment]
Sure, I thought of a side-script too.
So, do we need that? Or chat coordination is enough?

**Comment by iakat** [comment]
Right, we don't do external requests on the main script.
Me and @xPaw agreed to the leaderboard allowing external requests, because it's not the main file, and because I run steamga.me.

**Comment by xPaw** [comment]
We've already agreed not to work on autojoin scripts.
