### ISSUE TITLE
If you are in another Tab in Chrome and Refresh occurs it hangs till you switch to Tab

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [SteamDatabase/steamSummerMinigame#217]
I'm not 100% sure but it seems that if you are in another Tab while the Refresh occurs, it will hang till you switch back to the Tab, then it instantly Refreshes, else hangs there forever.

**Comment by Js41637** [comment]
Likely because of chrome, you cannot switch to another tab while running the script. Chrome assigns lower priority to Javascript in unactive tabs.

**Comment by xPaw** [comment]
See also https://stackoverflow.com/questions/6032429/chrome-timeouts-interval-suspended-in-background-tabs

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Hmm that's silly of Chrome, but lower priority is not hang till i switch to tab?

Well so opening another Instance then..

**Comment by Js41637** [comment]
This might also be because of Valves code which doesn't Tick while your not in the tab.

**Comment by xPaw** [comment]
We're ticking ourselves if renderer is throttled.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I detached Tab now, seems to be good this way, will w8 Refresh and watch... ;)

**Comment by Js41637** [comment]
You can't run the script anyway if the game isn't in its own Window. The whole script is timer sensitive so will not work at all in the background.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
@Js41637

Worked well in IE11, Firefox and also Chrome, only noticed that the Refresh hangs till i switch to Tab else everything is fine and runs in Background.

Also i don't see any difference of Tabs and detached Tabs, they are all single Tasks running anyway in Chrome.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Ok, i just watched a Refresh while in detached Tab running behind the others, so this seems to work.

I will now test if it really happens while in Tab and not focused.

EDIT: Yeah, definitely happens if not focused Tab also Chrome does almost pause the Tab if you switch, silly Chrome, this don't happen in IE and Firefox and its strange because no matter if detached or not its a single Task, so a bug of Chrome. Also it doesn't matter if Limit frames per second is enabled or not, so Chrome simply pause the entire Tab if attached and not focused.

**Comment by Sanaki** [comment]
This should likely be closed. It's a chrome "feature" with no workaround. Background windows retain full speed to allow for large- or multi-monitor setups, minimized and backgrounded tabs (tabs specifically not able to be viewed simply by window rearrangement) will have their js script fire rates reduced to 1/s. It's intended to prevent the multi-process design chrome uses allowing a high tab count to decimate CPU usage. In this case, it completely screws what this script is trying to do as well.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Yeah, it's only happening Chrome, there is an Workaround i read somewhere, but probably not applicable, so on Chrome simply detach Tab and don't minimize it.
