### ISSUE TITLE
Bookmarklet problem

### ISSUE THREAD

**Issue by Shadowfury22** [SteamDatabase/steamSummerMinigame#220]
Is it possible to fix the code to comply with Content Security Policy directives so this Bookmarklet...

javascript:(function(){document.body.appendChild(document.createElement('script')).src='https://raw.githubusercontent.com/SteamDatabase/steamSummerMinigame/master/autoPlay.user.js';})();

...doesn't give the following error on execution?

Refused to load the script 'https://raw.githubusercontent.com/SteamDatabase/steamSummerMinigame/master/autoPlay.user.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' http://steamcommunity-a.akamaihd.net/ https://api.steampowered.com/ http://www.google-analytics.com https://ssl.google-analytics.com https://www.google.com https://www.gstatic.com https://apis.google.com http://steamapi-a.akamaihd.net/ https://steamapi-a.akamaihd.net/ http://ajax.googleapis.com https://ajax.googleapis.com".

**Comment by xPaw** [comment]
No it's not possible.
