### ISSUE TITLE
Auto upgrade doesn't seem to work well

### ISSUE THREAD

**Issue by tleunen** [SteamDatabase/steamSummerMinigame#223]
Cybernetic Enhancements, level 1 sentry and Titanium mouse button are in yellow, but the script never purchase them.

Cybernetic is level 0, and it makes sense because it's not usefull. We have too much life already. But for the 2 others, I don't know why the script don't buy them when I have enough cash.

**Comment by rossengeorgiev** [comment]
The AutoUpgrade will only but the most cost effective item, it has certain priorities which are not visualized. The only problem is when you get all upgrades in high levels, it will wait for the most cost efficient option to be available, which might not happen before the day reset, and it would make sense to upgrade the lower tiers. This is not resolved yet.

The auto upgrade on HP will stop once you get above the 300k threshold, it's assumed everyone is spamming healing, so you should never really die, and it's pointless to put money in HP upgrades.

**Comment by tleunen** [comment]
And when I see my cash decreasing but no upgrades purchased? How is this possible?
Is it buying an upgrade I don't have access to?

**Comment by rossengeorgiev** [comment]
It's hard to comment without knowing the particular version you are using. There was an update to the feature just few minutes ago. If you see gold steadily decreasing, it could be sign of a bug, as server side doesn't seem to verify if you already own the particular thing. For example, you can purchase unlimited `Medics`, waste your gold. Check to see if disabling any of the toggles, changes the behavior.

I

**Comment by tleunen** [comment]
I'll try to provide more info next time, but I tested the script 4.6.2 and for me it buys only HP pack for now.. I have 11 light armor and 9 heavy armor.. nothing else :/

**Comment by tleunen** [comment]
Same thing with 4.6.3.

**Comment by tleunen** [comment]
Damn nevermind.. For whatever reasons, the checkboxes were unchecked...
I'll close this one and reopen a new issue if I still notice the weird behavior

**Comment by rossengeorgiev** [comment]
:clap:
