### ISSUE TITLE
Wormhole Total + Expected/Estimated Level

### ISSUE THREAD

**Issue by squee666** [SteamDatabase/steamSummerMinigame#224]
Is there anyway to implement the Total Wormholes in a Room to the Estimated and Expected level Count. So its more accurate

http://drx.pl/steamgame/    Seems to have been able to pull the total amount remaining per room . If you could also do this and have it update on a set interval to Add the amount the the Level expectation. We could get a better figure of what we might reach at end of countdown.

Is this plausible , thanks for reading

**Comment by iakat** [comment]
Not feasible, it'd take 1500 API requests and we don't want that.
