### ISSUE TITLE
Graphic bug with multiple raining gold

### ISSUE THREAD

**Issue by Cavey** [SteamDatabase/steamSummerMinigame#225]
Abilities seems to work well, constantly re-using medic in the right way.  Raining Gold, however, seems to have some sort of issue.

Issue:
1) Start the game with extra 100+ points to be able to spend on free abilities.  
2) Buy multiple (10x) raining gold to use when you get to bosses at level 60+.  
3) Load the script.  
4) Watch your raining gold go missing leaving a blank square that does nothing (but I assume is where raining gold would be).

Reloading the game shows the remaining raining gold correctly (10x).

Do not know if this is cosmetic or affects the way the script functions.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
This means Ability is being disabled(its not a Graphic Bug) noticed that too in 4.6.3 but then it was enabled again later permanently...

**Comment by xPaw** [comment]
Missing space means it's disabled.
