### ISSUE TITLE
Use absolutely all abilities (except wormhole) in last 15 minutes

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/steamSummerMinigame#226]
Ignore all checks, just use them all. Fun!

**Comment by GreatOldOne** [comment]
What's the problem with wormholes in the last 15 minutes? I still don't get it.

**Comment by xPaw** [comment]
You have to defeat a boss after using wormholes for badge to update.

**Comment by GreatOldOne** [comment]
It still needs to be removed from isNearGameEnd, because throw money still relies on it.
