### ISSUE TITLE
Is pData.hp current or max player hit points?

### ISSUE THREAD

**Issue by grimrebuke** [SteamDatabase/steamSummerMinigame#227]
I'm trying to craft up something that buys the most efficient armor I can afford if my health is below about 10% rather than spending money on armor upgrades if I'm not low on health.  However I'm having issues deciphering player health stats.

**Comment by rossengeorgiev** [comment]
Oh right, that's current HP.

**Comment by grimrebuke** [comment]
Is there a pData value for max?  If not, that is okay, I can set the value to something like 5k and probably be okay.  I just need to tweak the most efficient search to return the most efficient one I can currently afford.

**Comment by rossengeorgiev** [comment]
If you want max hp, `m_rgPlayerTechTree.max_hp`

**Comment by grimrebuke** [comment]
Thank you.  If you could sanity check the following I'd really appreciate it.
I added (or modified):  
        var pHealthPercent = pData.hp / m_rgPlayerTechTree.max_hp
    var upg_enabled = [
        enableAutoUpgradeHP && pHealthPercent < .20 ,
        ];
Then added the OR and condition following it to the section that appears to create the upgrade map list:
    if(upg.hasOwnProperty('required_upgrade') && s().GetUpgradeLevel(upg.required_upgrade) < upg.required_upgrade_level) || s().GetUpgradeCost(tree.idx) > pData.gold { return; }

Obviously I have to isolate this function from the DPS and click upgrade section or it would buy every upgrade it could afford regardless of efficiency.  I'm actually thinking of moving the entire check your health section to the medic function and bolting on the purchase of the most efficient and affordable armor to the end of that section as a fallback.

**Comment by rossengeorgiev** [comment]
`enableAutoUpgradeHP && (pData.hp / pTree.max_hp < .20 || pTree.max_hp < 300000)`

Might be a good idea.

**Comment by grimrebuke** [comment]
Nice.  Thank you.  Sadly I don't know where to find the logging/debugging information so I'm going to have to watch it to see if it is working.  Since I don't want to upgrade armor unless I'm wounded that would have to be an AND versus and OR, though.

**Comment by grimrebuke** [comment]
I've added a check for being below 30% health before using a pump up/medic/etc. directly to the useability function and submitted for approval.  I'm running into a wall with auto-purchasing armor only when injured so far.
