### ISSUE TITLE
Room pop

### ISSUE THREAD

**Issue by 1RV34** [SteamDatabase/steamSummerMinigame#23]
The highlight helps but as it has the same color as the other links in the breadcrumbs it might look as if it's clickable. Maybe it's not a big of a deal but if you got the time maybe think about giving it some tint or something.

**Comment by Ditti4** [comment]
Should probably make it the same color as "Monster Game" or just don't make it another breadcrumb but put it in braces.

**Comment by xPaw** [comment]
I`ll make it blue.

**Comment by 1RV34** [comment]
@Ditti4 it was the same like monster game before but it doesn't really show it well, highlighting it has benefits too but giving it the same color can have the effect of it feeling clickable

@xPaw thanks, you guys are doing a great job btw :)
