### ISSUE TITLE
AutoUprade: should adjust purchashing strategy when top tier upgrades get too expensive

### ISSUE THREAD

**Issue by rossengeorgiev** [SteamDatabase/steamSummerMinigame#231]
Otherwise it will get stuck at some point waiting for next level on the top tier upgrade. The player might never accumulate enough gold, so it makes sense to spend the gold on the lower tiers to get optimal DPS.

**Comment by OverlordQ** [comment]
instead of calculating value as "DPS increase / Cost"

Should look at "DPS Increase / ( Cost + Time_To_Save )" so it'll look at how long it'd have to do nothing to buy the upgrade vs other upgrades.

**Comment by Chdata** [comment]
Additionally, it seems like at the start it'll buy things in a pattern of like,

tier 1: 10 to 1 tier 2 items or so, depending on how the math works out

should just unlock level 10 of the highest tier possible, and from then on unlock based on the next best upgrade. Or rather, it should calculate buying tiers you don't even have unlocked yet, as opposed to only ones you have visible.

**Comment by rcaputo** [comment]
Copying from #280 

Goal: Use as much money as possible before having to throw it at the screen. Maximize click damage in the last desperate minutes of the day.

For each item tier (except the lowest):

Calculate how long it may take to purchase the next item at that tier (price / income-per-second).

Estimate the total increased damage of the purchased item for the game time remaining after the estimated purchase time. (dps \* (endgame time - purchase time)). It's zero if the purchase time >= endgame time.

Calculate how many items of the next lower tier can be purchased right now.

If lower-tier items can be purchased right now, estimate the total damage they'll do until the end of the game.

If the lower-tier damage exceeds that of waiting for the higher-tier purchase by some factor (e.g., 10%), consider purchasing the lower-tier item now.

**Comment by rcaputo** [comment]
The idea came to me while watching the script try to save up for another top-tier item in the last hour of the game.  It was hundreds of billions of moneys away from succeeding, and the current GPS wasn't sufficient to make it worthwhile.

**Comment by rossengeorgiev** [comment]
After some I thought I have come to the conclusion that this is not needed.
- There is no way to accurately measure gold gain (which is needed to adjust strategy)
- Games are going really fast (thanks to WH spam)
- Jumping to other game is essential
- If you things are going slow, you should jump, its not a one man game

So, all this makes `most cost effective` strategy the best choice. You just have to believe and let go of the wheel.

![a](https://cloud.githubusercontent.com/assets/2720787/8220290/245eaeb6-1549-11e5-9d90-607b08c7e876.png)
