### ISSUE TITLE
Spam wormholes on raining gold levels, and if level is dividable by 100

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/steamSummerMinigame#233]
> When used on every 100th level, will skip 10 levels with each use and grant the appropriate amount of gold.

**Comment by EdGruberman** [comment]
This should be the core strategy. I'm not sure why you want to wormhole on a raining gold, but every level divisible by 100 definitely.

Even if we only have 500 actives using the script with only 20 wormholes each, that is 100K levels we could potentially wormhole past. Which means level 10M is achievable if enough time is allowed to trudge through the 90 levels between each wormhole.

**Comment by russelg** [comment]
This is incredibly hard to coordinate however, seeing as the game is MUCH faster now.

**Comment by kaetemi** [comment]
~~Not sure if wormhole during raining gold would give any useful amount of extra coins. Might be a waste of raining gold instead.~~

~~I'd leave the gold farming bosses for gold-farming, and wormhole on %100 levels which are NOT raining gold~~ (and only start doing after > 5000 rush starts).

**Comment by EdGruberman** [comment]
Random distribution among script users, similar to elemental damage focus, should allow for a more even distribution of worm hole usage to minimize wormhole waste.

With potential of level 10M under ideal and perfectly coordinated circumstances, even a 10% success rate means level 1M.

**Comment by milkfat** [comment]
We need to use during raining gold in order to get the timing right. Wormhole isn't activated until _after_ the level is beaten. ~~I've seen us blow past levels divisible by 500, but spamming wormhole on every 1000th level seems like it would be reliable.~~

**Comment by kaetemi** [comment]
Ah wormhole after the level beaten. Nice. Is that confirmed to be the case? Then indeed on raining gold farming levels, yes.

**Comment by milkfat** [comment]
That's my experience. I used it a couple of times on the 1000s and the level continued until the boss was beaten. We immediately jumped 30 levels after the boss was beaten (seems a couple others also used wormhole).

**Comment by milkfat** [comment]
Just confirmed on level 10000. The boss remained and we jumped to level 10050 after it was defeated.

**Comment by XinhuanWHS** [comment]
[6/17 02:19:35] &lt;Drunken_F00l&gt; wormholes will stack in the same level
[6/17 02:19:42] &lt;Drunken_F00l&gt; it waits until end of level before applying

**Comment by allthefoxes** [comment]
Taking into account the above, wouldn't it be better to use them on *500 and *000 instead? So we can make sure all they WHs are off cd
