### ISSUE TITLE
The "time left" check is broken and the script is currently throwing all money away

### ISSUE THREAD

**Issue by lunboks** [SteamDatabase/steamSummerMinigame#235]
pretty catastrophic. the script is spamming Throw Money and as a result my upgrades are gimped

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I use v4.6.3 and it is not happening, still have 5 money throw items unused, so when does that happen and which version?

**Comment by xPaw** [comment]
Fixed in 3ed6d1e80f6948c27104df8f5311070c87d251d7 (4.6.5)

**Comment by lunboks** [comment]
it's not fixed in 4.6.5

**Comment by xPaw** [comment]
Are you sure? It is for me.

**Comment by russelg** [comment]
It has been fixed with latest update.

**Comment by lunboks** [comment]
Sorry, just updated again and it's fixed. Probably some caching there.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
So that was introduced between 4.6.3 and 4.6.5 then, not happening in 4.6.3
