### ISSUE TITLE
Save treasures until late game

### ISSUE THREAD

**Issue by russelg** [SteamDatabase/steamSummerMinigame#237]
Gold multiplies by level now, so it must be beneficial to keep them until late on.

**Comment by NoXPhasma** [comment]
Yes, the script still uses them immediately, that's a waste of gold.

**Comment by milkfat** [comment]
If the gold multiplies by level then it shouldn't matter when you use it. Yes, you'll get more gold on later levels, but upgrades will be proportionally more expensive (canceling out any benefit of waiting).

**Comment by GreatOldOne** [comment]
@milkfat Agreed. You will need their use in any level.

**Comment by rossengeorgiev** [comment]
It doesn't matter anymore.
