### ISSUE TITLE
Auto upgrade calcuation breaks no more abilities listed

### ISSUE THREAD

**Issue by CoolSilver** [SteamDatabase/steamSummerMinigame#246]
I've noticed the auto upgrade calculation breaks if all the abilities have been purchased but the option is still enabled. All other upgrades fail to highlight or purchase.

**Comment by Sanaki** [comment]
I noticed the highlights failing earlier, and sure enough, toggling off ability purchasing fixed the issue. My js is a bit too rusty to trust myself to fix it properly, but this needs to be addressed.

**Comment by rossengeorgiev** [comment]
When hilights fails, it doesn't mean auto upgrading is not working, just waiting.
