### ISSUE TITLE
Running script while window is minimized or in different tab

### ISSUE THREAD

**Issue by thelulzy** [SteamDatabase/steamSummerMinigame#247]
ensingm's script has now implemented a fix for this as of
https://github.com/ensingm2/SteamMonsterGameScript/commit/a173bea8adabd01f8ccbb66a7414a8f3d722408f

I can verify this to be true as I have 2 steam accounts in the same room and have witnessed one account deploy abilities while minimized and in another tab from the other account.

*Unrelated: I would suggest reopening issue https://github.com/SteamDatabase/steamSummerMinigame/issues/206 as I believe xPaw misunderstood the purpose when he closed it

**Comment by Xinayder** [comment]
The script does run when the tab is out of focus. I made a PR just now, and before I did it I had 40 wormholes. Now I have 37.

> I can verify this to be true as I have 2 steam accounts in the same room and have witnessed one account deploy abilities while minimized and in another tab from the other account.
> What's the problem?

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Does this also fix it for Chrome? Because i have this Issue only in Chrome not in Firefox or IE

**Comment by thelulzy** [comment]
I just tested with chrome, I believe I was confusing the presence of the issue with wchill's mod (which still is affected by minimization/tabs), as it seemed not to be an issue with this script.

Regardless, I'm not going to close this issue. I'll let someone else with the rights to do that close it to hopefully add visibility to the reopening of issue https://github.com/SteamDatabase/steamSummerMinigame/issues/206
