### ISSUE TITLE
Scope issue/suggestion

### ISSUE THREAD

**Issue by 1RV34** [SteamDatabase/steamSummerMinigame#25]
yes it's me again

you might also want to think about wrapping the js script to be cleaner and clutter the window object less and also has less chance of it colliding with existing variables by Steam (or variables that might exist in the future)

```
(function(w, s){
/* Init */
w.steamDbToolKit = {}; // im not good with names

/* Settings */
w.steamDbToolKit.whateverSetting = 3; // put editable settings like this, it can be changed using steamDbToolKit.whateverSetting = 3 in console then

/* Internal variables */
var yesImBusyOrWhatever = false; // this variable will only exist inside the wrapper

// rest of code
})(window, someOtherObjectYouMightWantToUse); // window becomes w inside the wrapper and the other one becomes s
```

edit: you might even could use that object to add your own functions in if needed

```
w.steamDbToolKit.showMeTheMoney = function(){}; // idk
```

**Comment by 1RV34** [comment]
noticing you to add the help wanted, does that mean you want external help or have questions or just want another steamdb dev to look at it? :P

i could make a pull request for it but a reformat like this might could become difficult to merge if changes happen after i started wrapping it

**Comment by xPaw** [comment]
See https://github.com/SteamDatabase/steamSummerMinigame#i-want-to-contribute

**Comment by 1RV34** [comment]
under what name would you want to have it?
is `autoScript` fine?

**Comment by xPaw** [comment]
There's no need to expose anything to `window`. See #19 for options.

**Comment by LeoVerto** [comment]
@1RV34 Are you still working on this?

**Comment by 1RV34** [comment]
My router didn't like the game so much and died but I came back a little while ago.
I still have a question open at https://github.com/SteamDatabase/steamSummerMinigame/issues/19#issuecomment-111741944 which I'd like to continue with first before this one is a good idea to pick up.

**Comment by xPaw** [comment]
You can just ignore `isAlreadyRunning` for now, we'll figure it out later.

**Comment by LeoVerto** [comment]
I think the name `steamDBScript` would work quite well.

**Comment by xPaw** [comment]
That's slightly generic, make it `SteamDB_Minigame`

**Comment by 1RV34** [comment]
you guys figure that out :P i'll pick it up after the localstorage one

**Comment by Xinayder** [comment]
`SteamDB_Toolkit`?

**Comment by xPaw** [comment]
localStorage can happen later, right now making it in anonymous function is a higher priority.

**Comment by 1RV34** [comment]
if i don't do localStorage before anonymous function, the config won't be accessable anymore

no worries it wont take long

**Comment by xPaw** [comment]
It doesn't matter if it's accessible or not.

**Comment by 1RV34** [comment]
okay i'll do this one first then XD
