### ISSUE TITLE
Akamai CDN throwing errors cause != steamcommunity.com

### ISSUE THREAD

**Issue by Autositz** [SteamDatabase/steamSummerMinigame#258]
As the akamai cdn is not in the allow list. Can be ignored or should be added? For you peeps to decide.
`XMLHttpRequest cannot load http://steamapi-a.akamaihd.net/ITowerAttackMiniGameService/GetGameData/v0001/?gameid=1&include_stats=0&format=protobuf_raw. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://steamcommunity.com' is therefore not allowed access.`

P.S. It seems to stop the script as well. (untested)

**Comment by welwood08** [comment]
This is not something we can fix, the error means that steamapi-a.akamaihd.net failed to allow the cross-origin request from steamcommunity.com. Since most of the time it does allow the cross-origin requests by sending the appropriate header, it's safe to ignore it.

**Comment by welwood08** [comment]
Also, if that's an unaltered error message and it really is trying to get data for game ID 1 then that's almost certainly safe to ignore because you won't want that data anyway.

**Comment by Autositz** [comment]
The gameid is altered as it is not relevant for the error message. The rest is as reported by Chrome.

Still.. i couldn't reproduce it but if the script really stops at that point then this is something that should not be ignored but caught and handled accordingly.

From my observation the script did not progress anymore as there were no more console log entries shortly after the error message.

**Comment by welwood08** [comment]
I had 5 of those errors in my console, game still playing fine. Could be because I'm running my responsiveness2 branch which alters quite a lot of the ticking mechanics (and catches errors, but if that was happening I'd have stack traces to look at).

**Comment by xPaw** [comment]
If you're using HTTPS Everywhere, you have to disable Akamai and Steam Static rules. We can't fix this.
