### ISSUE TITLE
Should we call DoClick sometimes?

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/steamSummerMinigame#26]
To clear crit queue and all that

**Comment by iakat** [comment]
Yes. Normal clicks seem to be a 100% crit chance after a while.

**Comment by xPaw** [comment]
I believe it's just queueing them up, so they show up on the next click.

**Comment by wchill** [comment]
I've been talking with a contributor on my fork. Crits are indeed queued up.

**Comment by xPaw** [comment]
Fixed crits.
