### ISSUE TITLE
Assign people to buy cooldown resets

### ISSUE THREAD

**Issue by Stanzilla** [SteamDatabase/steamSummerMinigame#261]
From http://steamcommunity.com/groups/MSG15WH/discussions/0/594820656456612292/

```
Q: But wormholes have a 1 minute cooldown. How can you get past level XXk?

A: That is why we have few players buying Like New items that reset everyones cool downs on the same lane. Then everyone can use wormhole every second if Like New is used every second.
```

now we could do the same as we did with locking in Elemental upgrades so lock in some people to buy cooldown reset items and auto buy wormholes on the others.

**Comment by HxxxxxS** [comment]
Everyone should buy a couple anyways

**Comment by rossengeorgiev** [comment]
The script uses specific probability to achieve more optimal use of `Like New` among all the players.
