### ISSUE TITLE
Past level 625 people need to use boss killing abilities on level 500 bosses (wormhole bosses).

### ISSUE THREAD

**Issue by Nishi77** [SteamDatabase/steamSummerMinigame#264]
They have too much hp.  It's best to use them after raining gold ends maybe.

**Comment by thelulzy** [comment]
This really depends on your room. This is not true for most of the competitive rooms, thus this implementation would not be ideal.

Some sort of timer might work. I've we've spent longer than x time, kill it, kill it with fire.

**Comment by xPaw** [comment]
We're doing WH strat now, which includes not killing bosses as long as possible.
