### ISSUE TITLE
Disable autoclick every 500 rounds... but wormholes every 100

### ISSUE THREAD

**Issue by EienSeihai** [SteamDatabase/steamSummerMinigame#266]
Stick with the wormholes every 100 rounds, but fix the autoclick every 500 rounds. You want disable autoclick every 100 rounds, not 500 if your wormhole rounds are every 100 rounds.

**Comment by EienSeihai** [comment]
For reference, the offending line is line 442. 

if(level > CONTROL.goldholeThreshold && level % 500 === 0) {
            advLog('Skipping autoclick on wormhole boss farm.');

should be 

if(level > CONTROL.goldholeThreshold && level % CONTROL.wormholeRounds === 0) {
            advLog('Skipping autoclick on wormhole boss farm.');

**Comment by MatthewClair** [comment]
I used isWormholeRound(level) rather than just using mod and fixed the error in a second location.  (Ignore the first commit it shows, I made a typo and I was too lazy to fix it an then squash so I remade the fork)

**Comment by xPaw** [comment]
Wormholes every 100 rounds happens in last hour, otherwise it's every 500.

**Comment by HxxxxxS** [comment]
Other scripts are using every 100 rounds. It doesn't really matter which
one you use, but everyone should be doing the same thing. If nothing else,
at least disable clicking at %100 levels and only use wormholes on %500

ons. 17. jun. 2015 kl. 09.08 skrev Pavel notifications@github.com:

**Comment by xPaw** [comment]
df940a003292c6121346ab19c29bcf77c8b0b1ab
