### ISSUE TITLE
Can we add "using steamdb fork" next to the version number?

### ISSUE THREAD

**Issue by Zazcallabah** [SteamDatabase/steamSummerMinigame#269]
Or something similar, just to make it easier to quickly figure out exactly which script you are currently running? The use case is 'suddenly everybody in chat yells stop using X start using Y script it is more updated' and I cant remember which script i currently have installed. ^^

**Comment by jabbink** [comment]
https://github.com/SteamDatabase/steamSummerMinigame/blob/master/autoPlay.user.js#L2

It already says that this is the SteamDB version of @mouseas script

**Comment by Zazcallabah** [comment]
No i mean in the game gui.
