### ISSUE TITLE
Cherry pick changes from wchill-master

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/steamSummerMinigame#27]

**Comment by wharwood** [comment]
#49 adds a pull request to add a wchill style info box to replace the close button tooltip

**Comment by wchill** [comment]
https://github.com/wchill/steamSummerMinigame/commit/f1dc5c8bb770e27ad9bd300b647b66710a075941

This provides a slow start mode to make joining the lobby easier, where autoclicks are disabled for the first 10 levels

**Comment by wchill** [comment]
https://github.com/wchill/steamSummerMinigame/commit/088a9e4c7ad497e76a172a0c0e7e8ddeb131259b
https://github.com/wchill/steamSummerMinigame/commit/db812e3951b835383760f9228d15e9dec2f6b472

These two commits allow the script to target bosses with nukes after level 1000, not just spawners. This is disabled every 200 rounds to allow Raining Gold to kick in

**Comment by wchill** [comment]
https://github.com/wchill/steamSummerMinigame/commit/234414ad2599ca0bf1a0ee38dc0250123463fab8

Check to see if level is divisible by 100, to space out Raining Gold. (Don't know if this strategy is optimal)

**Comment by iakat** [comment]
The slow start mode should definitely get merged by tomorrow start, perhaps limiting all of the script, and adding a few more restriction on items? (nuke, etc.)

**Comment by wchill** [comment]
At that point in the game, few people will have nukes (you need 2 treasures to get it that early). Probably want to disable offensive items anyway though

**Comment by wchill** [comment]
https://github.com/wchill/steamSummerMinigame/commit/f9378f84de4303a59ed38f40eda44095448199c2
https://github.com/wchill/steamSummerMinigame/commit/51f616ca6327600f85c7fea722078563b106c84d

These two commits add more UI removal options to improve performance.

**Comment by wchill** [comment]
That should be all the important changes, everything else is too old to really matter or is already integrated.

**Comment by hmmwhatsthisdo** [comment]
It might be worth it to also bring in the CSS/background fixes for the "Active Abilities" box that are implemented in wchill's script - FWICT he uses a custom background and tweaks the size of the abilities box so it doesn't clip.

**Comment by wchill** [comment]
^ above relevant commits I believe are

https://github.com/wchill/steamSummerMinigame/commit/46c343abf92699a780515e749c077cfab92c5972
https://github.com/wchill/steamSummerMinigame/commit/dce115584c5f158abc7423c2e7a59dfd5cda61bc
https://github.com/wchill/steamSummerMinigame/commit/7de060ea7e745120ebfbca673ce12900cec36856
