### ISSUE TITLE
Memleak? GPU / Tab going to 4GB RAM use

### ISSUE THREAD

**Issue by Autositz** [SteamDatabase/steamSummerMinigame#276]
Using Chrome and had it running over night, no clue how long it took till it got "full". But there seems to be a leak somewhere that results in ~4GB GPU and ~4GB Tab usage on my box.

No error or anything in the console at default debug lvl. Will raise it and see what happens next time. Tab was so unresponsive that even a reload did nothing but crash the chrome tab.

**Comment by HxxxxxS** [comment]
Did you have throttle renderer enabled? Did you have auto refresh enabled?
These are highly reccomended even if running script for short periods of
time. The game in itself is very data juice consuming.

ons. 17. jun. 2015 kl. 15.11 skrev Jean-Paul Rzyman <
notifications@github.com>:

**Comment by Autositz** [comment]
Yes, fps 1 is enabled and no autorefresh. Script is running from console only.

When i posted the issue i restarted and values are currently as follows:
![image](https://cloud.githubusercontent.com/assets/11299147/8208609/cb718250-1508-11e5-8011-ad16aa824a7e.png)
Already 500mb gpu and almost 700mb on the game tab.
Stuff is not happening when the game runs without the script.

By the time i finished this post GPU is almost at 600mb and the tab at 725mb both raising slowly.

**Comment by Sanaki** [comment]
The memory link is directly related to click rate. If you're not autoclicking without it, you wouldn't notice it. The original reason I got the script was to mitigate the memory leak without nearly crashing my computer. Autorefresh will help significantly, as will frame limiting and -especially- disabling particle effects. The last one isn't there to be easier on GPUs, it's there to prevent particles spawning and being left in memory.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
i let it run 48 Hours now without Restart 676MB GPU currently, 872MB Game Tab...

**Comment by Autositz** [comment]
Script is freezing/crashing Chrome without exception for me. Can't use it. :)
Restarted it couple of times in the past hours and it's already back to 1.3GB for tab and 1.1GB for GPU.

As it seems i am the only one with this problem... guess it will be ignored as the game is gone "soon" anyways.. unless valve brings a F2P entry for it in our libraries.. :D

**Comment by K4r0qtuYNE5G4qgZ** [comment]
@Autositz
I'm run this Script on Windows 7 with Chrome Version 44.0.2403.52 beta-m (64-bit) with Tamper Monkey for over 48 Hours without Restart and it now eats 1GB for Gametab and 680MB for GPU. It' may be alot, but my Firefox also eats sometimes over 4-6GB if i have a alot of open Tabs, so after 48 Hours running i consider this as not so much.
