### ISSUE TITLE
[Idea, Tweak] Boss Nuking Syncronisation above 5000? 10000?

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [SteamDatabase/steamSummerMinigame#277]
- Pick a Random Number from Range [0,1,2,3,4,5,6,7,8,9] and Assign one like Elements
- Disable the use of Nukes, Napalm, Clusterbombs, Cripple Monsters for Spawners!
- Nuke Boss with (Nukes, Napalm, Clusterbombs, Cripple Monsters) if Level.slice(-2, -1) matches
  the assigned Number only.
- Also perhaps Exclude Gold Rain Levels

This Way at least the Nuking will be distributed and Stuff not wasted all on Spawners and a Single Boss, this will Help distribute the Cooldown wait Time also and it can be optimized with the use of a Cooldown Item from Time to Time.

**Comment by rossengeorgiev** [comment]
Using WH strategy now, no nuking on bosses.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Well it was intended to speed 01-99 Levels only logically also it does'nt affect any x00 ones anyway, but game is over anyway, so..
