### ISSUE TITLE
don't hold out for top-tier items there's no time to afford

### ISSUE THREAD

**Issue by rcaputo** [SteamDatabase/steamSummerMinigame#280]
Goal: Use as much money as possible before having to throw it at the screen.  Maximize click damage in the last desperate minutes of the day.

For each item tier (except the lowest):

Calculate how long it may take to purchase the next item at that tier (price / gold-per-second).

Estimate the total damage of the purchased item for the game time remaining after the estimated purchase time.  (dps \* (endgame time - purchase time)).  It's zero if the purchase time > endgame time.

Calculate how many items of the next lower tier can be purchased right now.

If lower-tier items can be purchased right now, estimate the total damage they'll do until the end of the game.

If the lower-tier damage exceeds that of waiting for the higher-tier purchase by some factor (e.g., 10%), consider purchasing the lower-tier item now.

**Comment by SavageCore** [comment]
this should be discussed in #231

**Comment by rcaputo** [comment]
Closing this issue.  I copied the text of this issue to #231.
