### ISSUE TITLE
Auto upgrade DPS doesn't work properly with auto upgrade clicks enabled

### ISSUE THREAD

**Issue by Xinayder** [SteamDatabase/steamSummerMinigame#282]
Using the latest version, if you have auto purchase DPS and click upgrades enabled, the script will not buy all the DPS upgrades.

It upgrades Auto Cannon, then Advanced Targeting gets stuck on level 8, until either the user disables auto upgrade clicks or upgrade it to level 10. Same thing happens to other tiers past Auto Cannon.

**Comment by rossengeorgiev** [comment]
Because it prioritizes Click over DPS, in 4 to 1 ratio.

**Comment by Xinayder** [comment]
@rossengeorgiev Is that it? Because it looks like it isn't upgrading at all, and this happens since yesterday I think.

**Comment by rossengeorgiev** [comment]
https://github.com/SteamDatabase/steamSummerMinigame/blob/b6cc7bb4f1462f80fff2be53a1e9c24e4cf359f5/autoPlay.user.js#L632-L636
