### ISSUE TITLE
Since 3.8.2, autoclick fails on Gold Helm Boss

### ISSUE THREAD

**Issue by griftersly** [SteamDatabase/steamSummerMinigame#283]
Watched this happen 5 times in a row now. Every other boss acts normally, but when you get to Gold Helm the autoclick stops working. You only receive the kill reward. Switching to a click Macro does work and surprisingly the gold sticks, which makes me think this is happening to everyone (as the clicks wouldn't go through if everyone's auto was working).

I'm pretty sure it was working in 3.8.1. Still broken in 3.8.3. This is in both Chrome(tampermonkey) and Opera (violentmonkey).

Alright, 7 times now, 3.8.6 and 3.8.7 still have this problem. Submitting a screenshot shortly.

**Comment by xPaw** [comment]
Do you mean 4.8.2? And are these levels dividable by 100?

**Comment by griftersly** [comment]
Yes, that's what I meant. 4.8.2,4.8.3, 4.8.6, and 4.8.7
![bug](https://cloud.githubusercontent.com/assets/12940145/8214528/00838eea-14f8-11e5-98c3-cac8e96765c5.jpg)

I didn't check the level in question until you mentioned it, and it was on level 4000. They are divisable by a hundred.

**Comment by xPaw** [comment]
That's because we are doing wormhole strategy now. Every 100 levels, auto click is disabled to minimize damage to the boss.
