### ISSUE TITLE
[Annoying] Don't disable Abilities at all, User must stay in control

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [SteamDatabase/steamSummerMinigame#284]
It disables the Abilities every now and then for no apparent reason and exactly then when you need it you can't use it, i refresh Spam to enable them again, but honestly its not a Solution. Simple don't take Control from User if it's not absolutely needed!

Or implement at least #277 because its always disabled exactly when Boss needs to be kicked fast, and i don't mean Gold rounds, it happens to frequently (all 50 Levels or so) that everything is locked.

**Comment by rossengeorgiev** [comment]
![a](https://cloud.githubusercontent.com/assets/2720787/8215387/63bb4406-1527-11e5-8e89-1f540bb3b6c3.png)

**Comment by K4r0qtuYNE5G4qgZ** [comment]
No seriously, don't use Nukes and Stuff for normal Levels then because no one has some by the Time the Boss comes and also because all Abilities are disabled i can't fix it myself, so throwing Money at Screen is only Solution, which is also done by all, so i suppose many are affected.

**Comment by wn-mitch** [comment]
The strategy only works if everyone works in cohesion, which is why abilities are disabled. Just pucker up and let it happen.

**Comment by rossengeorgiev** [comment]
Trust in the lord

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Yeah, sorry if its stuck to a Boss for 2 Minutes something's wrong, also its exactly when all Abilities are locked, no wonder no one does anything and we have to w8 till some using other Scripts are nuking it or throwing Money at Screen to progress faster.

Costed us 500000 Levels easly already. Or does the Number recap later and its lag, i want know that.

**Comment by bountygiver** [comment]
I think with the current strategy, we can just leave them disabled only from x91 to x00, and leave them enabled for other levels

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Yeah, but still it would be cool to merge #292 in because then all is focused on Bosses after 10000 instead of wasting them on Spawner Levels which are skipped anyway within seconds... Me and some others patched it always in manually because it' really efficient, but we are only some People, would be nice if its in on the next Auto Update for all..

Also #292 does only disable the use of Nukes, Napalm and Clusterbombs  on non Boss Levels after Level 10000 and also use the same Routine Nukes for Napalm and Clusterbombs to make Things cleaner...

Also despite that all three are set on >50% Health for Bosses, they not trigger always together, because it changes to fast sometimes, which is good, because it distribute the use automatically a bit... But if it triggers together its also not bad too because it bleeds massively then...

**Comment by xPaw** [comment]
The point of this script is to automatically do stuff (like WH strat at the moment).
