### ISSUE TITLE
[BUG] Cooldown before Ability doesn't work anymore

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [SteamDatabase/steamSummerMinigame#286]
As of 4.8.9 it doesn't work anymore!

**Comment by xPaw** [comment]
It checks if there are any active cooldowns in the lane.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Ohh, ok, then its good, it was what i indended to do, ok i will watch it and look if it works...

So now it triggers the Cool down only if there is not already one? If so perfect! :)

**Comment by xPaw** [comment]
Yes it does

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Yeah, well was to fast then, sorry, only saw that things was triggered without... :)
