### ISSUE TITLE
Disabling Auto-clicking has minimal effect on bosses dying too quickly.

### ISSUE THREAD

**Issue by Stardrinker** [SteamDatabase/steamSummerMinigame#288]
Your average boss on higher levels takes several hours to kill if you only do click damage. It's the nuke-type abilities and possibly nuke bleed-through from previous rounds that would be causing the damage.

**Comment by Chdata** [comment]
Disable nukes 50 levels before a /100 level or something?

**Comment by Stardrinker** [comment]
Possibly 5-9 levels before boss farm. If we encountered a boss within 50 levels of a boss farm level, it would take hours to go past it. Trash mob health scaling is nowhere near what bosses are so it shouldn't be too bad to get past those 5-9 levels with auto-click damage.

**Comment by Sanaki** [comment]
Realistically even at full click dps from all players simultaneously I'm not sure how much of a threat it is to boss health totals with no damage abilities active. From a rough calculation and a healthy dose of assumptions at my current level (34,580), assuming 20x multiplier on both crit and elemental (and the right elemental of course) with guaranteed double crits on all 1500 players at 20 clicks per second, you'd still be looking at over half an hour taken to take a boss down. If I've somehow gone far astray with that math I encourage correction, but I don't believe I have.

For reference, used my current stats to derive that wild assumption. 611m base click, 201% crit rate with 20x crit damage, L14 (22x) air elemental, and a 36 quintillion base boss health.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Yeah, its also the Issue i have somehow too, they come to those Bosses and have no Nukes and nothing anymore, all wasted just before, even 4.8.9 throws nukes on normal Levels just before and then disables Abilities or has no Nukes left... Then you can starr at the Boss for Minutes after Minutes and watching the expected Level going down and down.

**Comment by Sanaki** [comment]
That's... not really the problem this issue is addressing.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
@Sanaki
Perhaps not exactly but what @Stardrinker or @Chdata said would help, the Issue i watch are very similar. Also Click Damage is way to low anyway to kick Bosses, you need Nukes, Napalm and Clusterbombs, else a bunch of Cripple Monster or as last Resort Throw Money on Screen which is like Cripple Monster but costs Money. So yeah save them for later or Syncronize the use.

**Comment by Stardrinker** [comment]
I've noticed that prep round threshold is 10, meaning that bosses 10 levels before boss farm rounds, i.e. 90, would be slowed down, which is probably not a good idea.

**Comment by irisfofs** [comment]
The script already tries to do that, though. At least in theory. Look at [line 1378](https://github.com/SteamDatabase/steamSummerMinigame/blob/master/autoPlay.user.js#L1378). 
Currently `rainingRounds = 100` and `rainingSafeRounds = 10`.

@Stardrinker It would, but remember that the whole reason we're trying this is to compensate for laggy ability use in the first place. That xxx90 boss is going to get wrecked by delayed ability activations from previous bosses.

**Comment by Stardrinker** [comment]
The issue is that disabling the autoclicker is pointless for prolonging boss fights on gold farm rounds, but it has an impact on how much gold people get. This DPS, while mostly useless on boss levels, does help on trash mob levels, letting us go up in levels a bit quicker.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
@Stardrinker 

Yeah, what i watched at #270 People throwed 50 Goldrain in at a xxx500 Level but Autoclicker was disabled, lost Billions for nothing, if the Boss stays there for so long then Autoclick, why disable it anyway.

**Comment by irisfofs** [comment]
Is it relevant at low levels, though? One thing that makes it tough to get started wormholing is that levels go by too quickly (maybe due to click DPS, maybe old scripts, maybe random people trying to "help", probably all of the above).

Could be useful to look at average DPS at low levels to figure out when to turn it back on.

Or (getting into unnecessarily complicated territory here) do something like assume all other players have your DPS and estimate time to kill the boss based on that, and turn off clicking if it's too fast. Though at the speeds it would matter, the 1s refresh rate would probably be too long already.

**Comment by Stardrinker** [comment]
At lower levels the autoclicker would have a larger impact since the cost scaling hasn't become so high, but I still think that it should give you ample time for Wormholes as long as the nuke-type abilities are disabled 5-9 levels beforehand.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I happened again on a xxx500 Level, well i edit the Script and take that out now, don't want loose Billions on every x500 Level for nothing...

**Comment by bountygiver** [comment]
I think it will be alright if dpc \* 20 \* 1500 < 1% of boss health. Then dpc is negligible and we can totally let it keep autoclicking, so people with low dpc can also take advantage of raining gold and have gold for HP upgrades

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Yeah, its difficult to calc anyway, but i don't think that Autoclicking has any big effect on Bosses anyway, but the loose of Money caused by it isn't good 

Also i noticed that Autoclicking isn't only disabled on 500 but also for all 100 Levels, is that intended?
