### ISSUE TITLE
Don't use worm hole again until all previous wormholes are finished

### ISSUE THREAD

**Issue by Chdata** [SteamDatabase/steamSummerMinigame#289]
Maybe the code already does this, but I'm too lazy to read.

Basically,

level xxx100, 1000 players use wormhole -> 10k level jump

don't try to wormhole again until the game is finished jumping to level x1x101

otherwise, some might be misfired at something like xx5101 or something

maybe they won't misfire though, idk.

**Comment by xPaw** [comment]
They stack.

**Comment by rossengeorgiev** [comment]
![a](https://cloud.githubusercontent.com/assets/2720787/8219070/5aa2d2cc-153f-11e5-844c-6fe45eb7688b.png)
