### ISSUE TITLE
[Questions] Are there still Goldrounds for MOD 250 Levels? WH Optimization Strategy and old/other Scripts.

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [SteamDatabase/steamSummerMinigame#290]
I ask the first because i saw about 50 People throw Goldrain in at a xxx500 Level at the same Time, but exactly then my Abilities was disabled and no Autoclicks made, so if there are still Goldrounds then please Autoclick else its a bit useless.

If not, then the other Issues i watched are probably because many use outdated or total different Scripts, so the newest is WH optimized, the others not, the newest Script locks all Abilities on regulary base for WH optimizations even if there are no more WH's.

Also a possibility to change Strategy would be nice, because how to guarantee there are only WH-Strategy Users in a Room, also sometimes 500 drop and 500 new ones comes in after a while, so you suddenly have another Situation, which needs other Strategy.

EDIT: Just now i had a 1100 drop and 1100 new Users, and suddenly they are throwing WH's again, really strange behavior and makes difficult to choice the right Strategy for the entire Time. I wonder if they move Users from one to another room Midgame, looks like because the Usernames throwing Stuff also change too.

**Comment by xPaw** [comment]
WHs happen every 100 levels.
