### ISSUE TITLE
[High Level Tweak] Remove the use of Napalm, Clusterbomb and Nukes for Spawners on High Levels

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [SteamDatabase/steamSummerMinigame#291]
I use the Routine for Nukes for all Three (Nukes, Napalm, Clusterbombs) and removed the else Statement below on all three to test and it Speed Things up drastically for High Levels.

So perhaps its a good Idea to skip the else Statement of all three on High Levels, because no need to care about Spawners there and we get so many Cooldown Items spammed that its skips the Bosses entirely with removed else Statement.

This way Nukes, Napalm, Clusterbombs are not wasted for Spawners that are dead within the next 100ms anyway and used on Bosses.

**Comment by rossengeorgiev** [comment]
Fixed in 5d32f8d2df8696d5c8ae58ff92c47cbc09a22989

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Nope doesn't fix it, isn't the same as #292 tweak that disables use of for non Boss after 10'000 so flows goes on and stuff saved only for Bosses else stucks, its tested over 15 Hours now... on last game and this one, we manually patch it in after each update because it was still not merged yet...
