### ISSUE TITLE
[Problem] Change Enable Offensive Ability default to True not False for away People getting Auto-Update

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [SteamDatabase/steamSummerMinigame#296]
Consider to enableOffensiveAbilities default to True instead False if away People get updates and are unaware of change.

Our Room Level goes considerabely down since last update, suppose its because many away People got Auto-Update and its disabled by default... Lost 112K and falling... Lost 128K and falling... Lost 135K and falling... Lost 140K and falling... Lost 148K and falling... No one uses Abilities anymore...  Lost 154K and falling.. Lost 175K and falling.. Ok forget it Auto Updates are normally set to 1 Hour Interval, so not fun! Lost 215K and falling... I see it was changed... but still Lost 254K and falling... Will have to wait till they get the update, till then i will probably change room because it's over now... Its also over 345K lost now...

Btw. does this also affect Nukes, Napalm and Clusters? Because they also seized to show up in Ability List?

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Ok, Abilities are again coming in Ability List we again gain Levels 15K so far gained... But i suppose it will some time till all are getting updated... The Flow was interrupted... LOL!

Also funny what a little Boolean can cause isn't it? ;)

**Comment by rossengeorgiev** [comment]
Yep. Probably wasn't a good idea. Anyway fixed in 7c1ef5c28bc4d3688b59f43db9839cdca70bb2cf
