### ISSUE TITLE
WH Analysis does not account for trolls

### ISSUE THREAD

**Issue by cheapsteak** [SteamDatabase/steamSummerMinigame#300]
Trolls have setup scripts to use WHs both seemingly at random and also at every 99th level.  

Goldhelms are almost not seen except by chance when multiple trolls just happen to spam the correct number of WHs to get to 100  

Would have to either coordinate WH usage to counter (e.g. trolls activate 3 WHs at level 99, ~97 bots would then have to activate a WH each to get to another 100)  

Otherwise everyone could just spam WHs regardless whether it's a 100 level, and there'd be a ~1% chance of ending up on a 100 level anyway

**Comment by iakat** [comment]
`onTrollDetected(callback)`

**Comment by rossengeorgiev** [comment]
```
> canWeHaveNiceThings()
< False
```
