### ISSUE TITLE
Autoclicking Level -00 Bosses

### ISSUE THREAD

**Issue by Iamshakes** [SteamDatabase/steamSummerMinigame#301]
The latest script keeps autoclicking the bosses at the levels that increment in 100s. It appeared this morning, yesterday's scripts were working correctly. 

Other thing i noticed is the script just doesn't use raining gold ever. I end up with 500+ at the end of the game.

**Comment by bountygiver** [comment]
the autoclicking should not increase boss dying speed, as the script will make sure that you yourself cannot click boss to death in 1500 days with 100% crit chance first before decide that you can auto click and benefit on raining gold.

**Comment by rossengeorgiev** [comment]
Autoclicking is selectively disabled on bosses depending on DPS. Either way, if you update to the latest version, you even go to the boss lane. This is intended.
