### ISSUE TITLE
gold helm boss bug

### ISSUE THREAD

**Issue by MurkBRA** [SteamDatabase/steamSummerMinigame#303]
When this boss appears the auto lane select get bug then select lane 1 (if boss on lane 1 it changes to lane 2) even it is empty.

**Comment by NolanSyKinsley** [comment]
That is intended to prevent the Like New ability giving nukers more nukes and killing Goldhelm

**Comment by iakat** [comment]
> That is intended to prevent the Like New ability giving nukers more nukes and killing Goldhelm

**Comment by aviraccoon** [comment]
Not that it helps anyway (hi 47030)
