### ISSUE TITLE
EDIT: Spending skills while in an empty lane.

### ISSUE THREAD

**Issue by Llorx** [SteamDatabase/steamSummerMinigame#304]
Now there are 3 lanes and one with a boss monster. The script is stuck at lane 1, without any monster, and seems that everyone is using the same script because in this empty lane there are 800 players with 2000x metal detector (wtf!) and 300 players in the other lanes.

The script must check in different ways if there is any monster in the lane so don't gets stuck. In a small script that I used before discovering this one I had written this small function:

```
function laneHealth(lane) {
    return parseFloat(document.getElementById("lane" + lane).getElementsByClassName("bar")[0].getElementsByTagName("div")[0].style.width.replace("%", ""));
}
```

And works like a charm. Maybe this script can use this in addition of his own system.

EDIT: And happened again: http://i.gyazo.com/0f036abe879adf812329dbd457c505f2.jpg

1 minute in the level and the boss in lane 3 with maximum health bar... we are going to get stuck here forever xD

EDIT2: All the times that happens the level number is a multiple of 100 and the lane that is not empty has a boss.

**Comment by Llorx** [comment]
Just checked the source code and noticed a code inside function `goToRainingLane()` that says something about WH level and changing to a lane without boss. Don't know why this behaviour is forced and why is spending skills while in the empty lane.

Obviously going to an empty lane instead of killing the boss is for a reason, but I think that spending skills while in the empty lane (metal detector-reset skills-metal detector-reset skills-again-again-and again...) is a bad behaviour.

**Comment by rossengeorgiev** [comment]
The script uses WH strategy and tries not to damage bosses in order to stack maximum WHs.

Read her: https://github.com/SteamDatabase/steamSummerMinigame/blob/master/Analysis%20of%20WH%20spam%20strategy.ipynb

**Comment by Llorx** [comment]
Kinda good strategy, but how can the script control moving to a new game? Because all I see is get stuck for some minutes and then keep moving without changing game.

EDIT: Seems that I have to control that manually. Ok.

Thank you!

**Comment by HxxxxxS** [comment]
it is to not kill the bosses so we can spend as many wormholes as possible
