### ISSUE TITLE
The game's over...

### ISSUE THREAD

**Issue by thelulzy** [SteamDatabase/steamSummerMinigame#307]
and now I'm bored.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
i can feel you.

**Comment by jabbink** [comment]
Please refrain from using the GitHub issues feature to report other things than issues with THIS project.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Well Project is done anyway and all related ones - Game Over - Scripts can be deleted now...

**Comment by jabbink** [comment]
Yeah, but I am subscribed to this repo not for getting updates about the game, but for receiving updates about the code in this project.

I know that it's over and it's fine that you did this; it was more meant as a reminder that this website (GitHub) is used for more than banter about the Steam Summer Game.

@SteamGame maybe you can disable issues for this repo.
