### ISSUE TITLE
Add a script that is executed on /minigame/ page to auto-join games

### ISSUE THREAD

**Issue by Xinayder** [SteamDatabase/steamSummerMinigame#33]
I started writing a script that replaces the big green button on the /minigame/ page when you're going to play for the first time function with one that auto-joins a game and ignore errors. It also adds a button that allows you to choose a room to join.

It's in here, in case anyone wants to take a look: https://gist.github.com/RockyTV/5a6cd3e37283a6126e9b

What do you guys think about it? Should we add it to the repository?

**Comment by sithrebel15** [comment]
If this is added and works correctly I can add functionality that updates the script and reloads the page.

**Comment by 1112e** [comment]
If you already have a code then why not create a pull request?

**Comment by Jaglag** [comment]
would be nice to have to join the rooms faster

**Comment by Xinayder** [comment]
I talked to xPaw and he said it's a bit out of the scope of the project.
Up for discussion.

**Comment by Jaglag** [comment]
could you bring it in tempermonkey format then and release it so i use it as seperate script cause everytime i reload page i have to activate it again @RockyTV 

Ty

**Comment by Xinayder** [comment]
Setup a repository for it: https://github.com/RockyTV/steamMinigameAutojoin

@Jaglag test it, and see if it works. If it does not, create an issue on the script repository (listed above).

**Comment by Jaglag** [comment]
imported it and looks like its working (hopefully) i test it when new round start dont have a second account for that

**Comment by xPaw** [comment]
I will close this, as you've setup your own repository for it.
