### ISSUE TITLE
Use Resurrection ability if more than half of the players on the lane are dead

### ISSUE THREAD

**Issue by Xinayder** [SteamDatabase/steamSummerMinigame#40]

**Comment by wchill** [comment]
I'd say this isn't always optimal, such as if players have been AFK for so long that they haven't upgraded armor and will die quickly even with resurrection.

Maybe take into account number of active players?

**Comment by PxlBuzzard** [comment]
If auto-buying of upgrades was implemented then you wouldn't need to worry quite as much about AFK. But an active player check would be a good idea either way.

**Comment by ghost** [comment]
What do you guys mean by 'active'? I'm not sure if there's a way to see the number of players who are signed out. I have a resurrection policy on mouseas: https://github.com/mouseas/steamSummerMinigame/pull/61. Check out `useReviveIfRelevant()`
