### ISSUE TITLE
Investigate whether abilities stack

### ISSUE THREAD

**Issue by LeoVerto** [SteamDatabase/steamSummerMinigame#42]
If not, we shouldn't apply them when already active in the lane.

**Comment by wharwood** [comment]
Decrease Cooldown's tooltip explicitly states that it does not stack.

**Comment by iakat** [comment]
@loserwill That has been dealt with by disabling it when active on lane.

**Comment by sithrebel15** [comment]
Raining Gold stacks.

**Comment by wchill** [comment]
Yep, Raining Gold definitely stacks. 160 Raining Gold on level 20 = glorious

**Comment by iakat** [comment]
I think we have a pretty good idea of what stacks and what does not by now. Closing this.
