### ISSUE TITLE
Syntax, misplaced closing bracket 

### ISSUE THREAD

**Issue by Chirimorin** [SteamDatabase/steamSummerMinigame#51]
At the end of the script, a closing bracket is misplaced. 

Currently the code reads

```
(function(w) { 
    //code
}(window));
```

This should be 

```
(function(w){
    //code
})(window);
```

The code still runs fine, so it's a very minor issue

**Comment by xPaw** [comment]
It's not a mistake. See https://stackoverflow.com/questions/3384504/location-of-parenthesis-for-auto-executing-anonymous-javascript-functions

**Comment by Chirimorin** [comment]
Ah, I did not realize that this is also valid. I've only ever seen the second way.
