### ISSUE TITLE
Investigate Critical Damage + Elementals Stack

### ISSUE THREAD

**Issue by kratsg** [SteamDatabase/steamSummerMinigame#57]
A bunch of us in Reddit #2 have seen that increasing elemental damage does not affect critical click damage. If so, elementals are somewhat pointless?

**Comment by wchill** [comment]
Yes, I just noticed this. However, elementals still are not pointless, it just means that you should only specialize in one. The crits will allow you to partially make up for the other 3 elements.

**Comment by kratsg** [comment]
@wchill - where it starts getting hazy is the end-game. It's pretty clear that passing 10k is going to be close to impossible as it is. And the next round of games will end up having people with 100% crit, which means focusing on damage+crit is probably what gets us through the 10k hurdle.

**Comment by wchill** [comment]
Verified that crits and elements do not stack.

Optimal strategy would be to have crits >= elements (as long as crit chance is good, maybe 50%?)

Lucky Shot + Elements upgrade base damage by same amount per level, so the numbers come out to this:

25% chance: elemental damage
75% chance: no elemental damage

In that 75% chance, we have a chance of rolling a crit. If this is 50%, then 50% of the time we will do the same amount of damage as elemental damage.

So average DPS in this situation is (25% + (75% \* crit chance)) \* multiplier \* base DPS, assuming the element upgrades are stacked and upgrade levels are the same.

**Comment by kratsg** [comment]
@wchill Most people are going to have 100% critical chance today. This means that it's almost nearly impossible to make elemental damage as good.

**Comment by kratsg** [comment]
![screenshot 2015-06-14 12 27 03](https://cloud.githubusercontent.com/assets/761483/8149649/e3848290-1290-11e5-9a68-33b41b8a1b70.png)

If you look here, is the crit damage going up by 1x or 1.5x? This is not clear at all. A bug?

**Comment by Sanaki** [comment]
Someone with better visibility may want to confirm, but I believe as of the current day's game version, crits multiply elemental bonuses just fine.
