### ISSUE TITLE
Add Cripple Monster usage

### ISSUE THREAD

**Issue by wchill** [SteamDatabase/steamSummerMinigame#59]
Right now only Cripple Spawner is being used. We should add Cripple Monster for use on boss levels, for example.

**Comment by wchill** [comment]
Check this https://github.com/wchill/steamSummerMinigame/commit/b89201c1b9ae9e38640241064a4bd51a68cea923

**Comment by iakat** [comment]
Closed as of ae28681c7844aa306b970cedc41891ae676d51b0.
