### ISSUE TITLE
Ignore raining gold on trash mobs late-game

### ISSUE THREAD

**Issue by rannmann** [SteamDatabase/steamSummerMinigame#77]
Probably anything past level 1500 (or 10 railgun + 10 mouse button + 20 elemental damage levels) isn't worth switching to the raining gold lane unless Max Elemental Damage is also active.  Prioritizing quick group levels by focusing on users' elemental spec will yield far more gold on bosses than anything one could gather from trash lane gold clicks.

**Comment by rannmann** [comment]
Nix the level thing.  Maybe wait 10 hours instead.

**Comment by HxxxxxS** [comment]
I vote for a level thing

**Comment by iakat** [comment]
No longer necessary.
