### ISSUE TITLE
Add auto bonus item buying for round start

### ISSUE THREAD

**Issue by Cyborgmatt** [SteamDatabase/steamSummerMinigame#79]
This area needs speeding up, especially as we acquire more bonus points each day.

**Comment by ghost** [comment]
I got this working on the main mouseas repo. Not sure what needs to be changed to make it compatible with this fork, and it needs more testing, but here ya go https://github.com/mouseas/steamSummerMinigame/pull/78. Bulk of it is in `purchaseBadgeItems()`

**Comment by Marlamin** [comment]
░░░░░░░░░░░████ 
░░░░░░░░░░░█░░█ 
░░░░░░░░░░█░░░█ 
░░░░░░░░░█░░░░█ 
███████▄▄█░░░░░██████▄ 
▓▓▓▓▓▓█░░░░░░░░░░░░░░█ 
▓▓▓▓▓▓█░░░░░░░░░░░░░░█ 
▓▓▓▓▓▓█░ Valve~ Add This░░░█ 
▓▓▓▓▓▓█░░░░ Please! ░░░░░█ 
▓▓▓▓▓▓█░░░░░░░░░░░░░░█ 
▓▓▓▓▓▓█████░░░░░░░░░█

**Comment by xPaw** [comment]
This was done.
