### ISSUE TITLE
New Weapons!

### ISSUE THREAD

**Issue by kratsg** [SteamDatabase/steamSummerMinigame#84]
![screenshot 2015-06-14 11 51 17](https://cloud.githubusercontent.com/assets/761483/8149534/b2b2b9d4-128b-11e5-9660-eb87dd54a4e9.png)

**Comment by xPaw** [comment]
Yes we know, what's the point of this issue exactly?

**Comment by kratsg** [comment]
The critical click damage was incorrect for it I think. It's not 100% clear since the numbers reported there do not match up with Lucky Shot.
