### ISSUE TITLE
Enhancement: Show lane stats

### ISSUE THREAD

**Issue by 1RV34** [SteamDatabase/steamSummerMinigame#86]
basically have a toggle option to show off the stats like here https://github.com/kton/steam_mss2015
it tells more than just...stuff happening

**Comment by wchill** [comment]
I am working on this in my fork and will push here when complete.

**Comment by ElDiabloWar3Evo** [comment]
Any profgress wchill ?

**Comment by kton** [comment]
I've updated the DOM injection method for compatibility with the autoclicker scripts in v0.0.2.

You're welcome to incorporate your own lane stat functionality...
but note that both scripts should now be able to run in tandem without conflicts. :v:

Keep up the good work! :thumbsup:

**Comment by iakat** [comment]
@wchill :japanese_goblin:

**Comment by wchill** [comment]
@chauffer it's being worked on https://github.com/wchill/steamSummerMinigame/tree/lane_info
