### ISSUE TITLE
Click Rate too low

### ISSUE THREAD

**Issue by ewright352** [SteamDatabase/steamSummerMinigame#91]
The allowed click rate for the game is now 20, but it's only set to 10 in this script.

If you set to 20 manually, you'll notice the returned crit values double. Crit values don't continue to increase after 20. Therefore, 20 looks like it's the max.

**Comment by wchill** [comment]
Can someone review PR #93? Fixes this.

**Comment by wchill** [comment]
Closed - see discussion in #93.
